version: "3.8"

services:
  db:
    image: mysql:9.0.1
    container_name: linksdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=linksdb
      - MYSQL_USER=fazt
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./mysql-data:/var/lib/mysql  # Mount the data directory for persistence
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql  # Initialize the database with SQL script

volumes:
  mysql-data:
